name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master, main]

env:
  NODE_VERSION: '20.x'

jobs:
  lint-and-type-check:
    name: Lint and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure npm retry for network flakiness
        run: npm config set fetch-retry-maxtimeout 60000 && npm config set fetch-retry-mintimeout 20000 && npm config set fetch-retries 5

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type check
        run: npm run type-check

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier formatting
        run: npx prettier --check .

  test-api:
    name: Test API Backend
    runs-on: ubuntu-latest
    needs: lint-and-type-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure npm retry for network flakiness
        run: npm config set fetch-retry-maxtimeout 60000 && npm config set fetch-retry-mintimeout 20000 && npm config set fetch-retries 5

      - name: Install dependencies
        run: npm ci

      - name: Run API tests
        run: npm test --workspace=apps/api
        env:
          CI: true
          NODE_ENV: test

  test-mobile:
    name: Test Mobile App
    runs-on: ubuntu-latest
    needs: lint-and-type-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Configure npm retry for network flakiness
        run: npm config set fetch-retry-maxtimeout 60000 && npm config set fetch-retry-mintimeout 20000 && npm config set fetch-retries 5

      - name: Install dependencies
        run: npm ci

      - name: Run mobile tests
        run: npm test --workspace=apps/mobile
        env:
          CI: true

  build:
    name: Build Applications
    runs-on: ubuntu-latest
    needs: [test-api, test-mobile]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared package
        run: npm run build --workspace=packages/shared

      - name: Build API
        run: npm run build --workspace=apps/api

      - name: Upload API build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: apps/api/dist/
          retention-days: 7

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint-and-type-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Check for vulnerabilities
        run: npx audit-ci --moderate
        continue-on-error: true

  coverage:
    name: Test Coverage
    runs-on: ubuntu-latest
    needs: [test-api, test-mobile]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: |
          npm run test --workspace=apps/api -- --coverage
          npm run test --workspace=apps/mobile -- --coverage
        env:
          CI: true

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            apps/api/coverage/
            apps/mobile/coverage/
          retention-days: 7
