name: Release to Main

on:
  # Manual trigger
  workflow_dispatch:
  # Open/update a PR to main whenever master is updated
  push:
    branches: [ master ]

jobs:
  open-release-pr:
    name: Open PR from master to main
    runs-on: ubuntu-latest
    steps:
      - name: Create or update release PR
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const title = 'Release: Merge master into main';
            const body = 'Automated release PR to update production (main) from master.';
            try {
              const existing = await github.rest.pulls.list({ owner, repo, state: 'open', head: `${owner}:master`, base: 'main' });
              if (existing.data.length > 0) {
                core.info(`Existing release PR #${existing.data[0].number} already open.`);
                return;
              }
              const res = await github.rest.pulls.create({ owner, repo, title, head: 'master', base: 'main', body, maintainer_can_modify: true });
              core.info(`Created release PR #${res.data.number}`);
            } catch (error) {
              if (error.status === 422) {
                core.info('Branches are identical or PR already exists.');
              } else {
                core.setFailed(error.message);
              }
            }

