name: Security Audit

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  security-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Configure npm retry for network flakiness
        run: npm config set fetch-retry-maxtimeout 60000 && npm config set fetch-retry-mintimeout 20000 && npm config set fetch-retries 5

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: |
          npm run security:audit --workspace=apps/api
          npm run security:audit --workspace=apps/mobile
        env:
          MAX_ALLOWED_SEVERITY: high

      - name: Run dependency check
        run: |
          npm audit --audit-level=high --workspace=apps/api
          npm audit --audit-level=high --workspace=apps/mobile

      - name: Secrets scanning with gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      - name: SAST with Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/secrets
            p/owasp-top-ten
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

      - name: Upload security results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-audit-results
          path: |
            security-audit-*.json
            semgrep-results.json
            gitleaks-report.json

      - name: Comment PR with security summary
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            let comment = '## 🔒 Security Audit Results\n\n';

            try {
              // Add audit summary if available
              comment += '✅ Security audit completed successfully\n';
              comment += '✅ No high-severity vulnerabilities found\n';
              comment += '✅ Secrets scanning passed\n';
              comment += '✅ SAST analysis completed\n';
            } catch (error) {
              comment += '❌ Security audit failed - please review the logs\n';
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
